### ISSUE TITLE
Final prep steps to be able to release QA 4.0 with the linked data extended context

### ISSUE THREAD

**Issue by elrayle** [samvera/questioning_authority#205]
Remaining steps for the major release of QA 4.0:

- [x]  move documentation from README to wiki
- [ ] determine if any new documentation is required for the new extended context feature
- [x] review two open PRs (#157, #196) to determine if they should be merged or closed
- [x] review open issues to determine if any are required for the next release
- [x] review changes that make this a major release to determine if any deprecations are required
- [x] remove existing deprecations (PR #209)
- [x] fix incorrect processing for IriTemplates (PR #208)

**Comment by elrayle** [comment]
RE: Any deprecations needed?

A deprecation was added for the conversion from config format 1.0 to 2.0.  It only warns when a config was in the 1.0 config style.

The refactoring that moved classes around will not be backward compatible which is the reason this is a major release.  They are functionally backward compatible, so using QA you will not see a difference.  But they are not code backward compatible, since the classes moved and have different names and some methods live in different classes.

**Comment by elrayle** [comment]
4.0 has been released
