### ISSUE TITLE
Remove deprecated code

### ISSUE THREAD

**Issue by elrayle** [samvera/questioning_authority#289]
### Description

Remove deprecated code in preparation of next major release.  

### TODO

- [ ] update all fixture configs to use ldpath instead of predicates -- PR #284 (lod_lang* only)
- [ ] update query and find to no longer reference predicates (i.e. `/lib/qa/authorities/linked_data/search_query` and `find_term`)
- [ ] remove config processing of predicates (i.e. `/lib/qa/authorities/linked_data/config/search_config and term_config`)
- [ ] remove services supporting predicates (search `/app/services` `deprecat` to find services to be updated)
- [ ] remove any other deprecations (search entire qa for `deprecat`)

### Related Work

PR #284 updates fixture configs related to language processing to use ldpath
